### ISSUE TITLE
Consider making the method public

### ISSUE THREAD

**Issue by drugilsberg** [GT4SD/zberta#1]
https://github.com/GT4SD/zberta/blob/1968b40ca9ab1ee5f4e65b0d295f80ab18f4e0bb/src/zberta/intent_discovery/zberta.py#L27

Since the method is used also in the example, I would consider removing the prepended `_`.

**Comment by comidan** [comment]
Yes, I agree. It's important to make it public now that it can be used as a complete working pipeline. (before it was private just for testing reasons).

Will do commit later on this day!
Thank you!

**Comment by comidan** [comment]
Issue solved with commit [825fed0](https://github.com/GT4SD/zberta/commit/825fed0167749cba69dd25b232ec4900d5a5221c).
