### ISSUE TITLE
Need to train the model on any other dataset other than Banking

### ISSUE THREAD

**Issue by abdullahaijaz** [GT4SD/zberta#10]
Hi @comidan, Thanks again for making this pipeline open-source.
I have two concerns.

1. Whether the model is using both datasets (SNLI and Banking77-OOS) or it’s only using SNLI for the training? if yes, then can you please point out where and how is it used in the code?

2. It is related to the 1st one as well. Actually, I need to train the BERT-A model with any other dataset other than Banking77-OOS to generate unknown intents. Can you please guide me on how to do that?

**Comment by comidan** [comment]
Hello @abdullahaijaz I'm sorry to reach you so late, anyway I'll answer your questions here below.

1) The model is trained using SNLI in one version, and in another version is trained/fine-tuned using Banking-77-OOS you can see it in the provided examples where you could just use the provided class [DataBanking](https://github.com/GT4SD/zberta/blob/4adbbdd8dd5e381a121bcf7133f3abc14621e3f4/src/zberta/data/data_banking.py#L12)

2) yes of course, everything is based on PyTorch, so it's pretty straightforward but if you wish to use the [DataPreparation](https://github.com/GT4SD/zberta/blob/4adbbdd8dd5e381a121bcf7133f3abc14621e3f4/src/zberta/data/data_preparation.py#L8) class you can easily implement a new one, but that's not strictly necessary as I said.

If you need any further help, please ask!
