### ISSUE TITLE
Error while running sample code on Colab

### ISSUE THREAD

**Issue by javaidnabi31** [GT4SD/zberta#3]
---> 15 z_intents = unknown_intents_set("en_core_web_trf", z_dataset['test']['text'])
     16 berta = model.instantiate_model(z_banking.labels(), z_banking.output_dim(), device, model_name,
     17                                 z_banking.nli_labels(), path="model.pt", dict=True)

[/usr/local/lib/python3.7/dist-packages/zberta/intent_discovery/unknown_intents.py](https://localhost:8080/#) in unknown_intents_set(dataset, spacy_model)
     15 def unknown_intents_set(dataset, spacy_model=None):
     16     global nlp_engine
---> 17     if spacy_model is not None and spacy_model not in default_spacy:
     18         os.system("python -m spacy download " + spacy_model + " --no-deps")
     19         nlp_engine = spacy.load(spacy_model)

TypeError: 'in <string>' requires string as left operand, not list

**Comment by comidan** [comment]
Hello @javaidnabi31 , thank you for pointing out this issue!
It's been solved, unfortunately an optional parameter indicating the spaCy model to be used was left in a wrong order after a change in this [method](https://github.com/GT4SD/zberta/blob/4b9d21f8b2c319eba283f8ba917b40aaa8d62552/src/zberta/intent_discovery/unknown_intents.py#L15).

Now the sample code on Colab has been fixed.

Thank you!
